driver:
  name: vagrant
  synced_folders:
   - ["~", "/dir", "create: false"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
    driver:
      gui: false
      provision: true
      vagrantfiles:
        - test/provision/vagrant_debian.rb
  - name: windows-2012r2
    driver:
      gui: false
      box:  mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[atom]
      - recipe[apm_packages]

verifier:
  name: inspec
